### ISSUE TITLE
Fail to init Orchestrate if not vault is defined

### ISSUE THREAD

**Issue by ggarri** [ConsenSys/orchestrate-helm#20]
To use QKM with AWS KMS as the Vault store, should I leave the agents as empty array? QKM stuck at looking for serviceaccount vault

```
Error creating: pods "quorum-key-manager-789c7f56fc-" is forbidden: error looking up service account orchestrate/vault: serviceaccount "vault" not found
```

Settings
```
    vault:
      tls:
        enabled: false
```

More context
https://consensys.slack.com/archives/C02FYJ9S9A8/p1644303451254499

**Comment by 6l20** [comment]
This issue has never been reproduced. Tried with existing and fresh clusters. QKM Chart v1.1.8.
However a proper way to disable agents is to explicitly make the following statement in values :

```
vault:
  tls:
    enabled: false
  agents: {}
``` 
Not doing so might cause an issue when using our kubernetes exemple with the following error :

`in ./helmfile.yaml: in .helmfiles[0]: in ./helmfile-core.yaml: failed processing release quorum-key-manager: failed to render values files "values/qkm.yaml.gotmpl": failed to render [values/qkm.yaml.gotmpl], because of template: stringTemplate:135:19: executing "stringTemplate" at <.Values.vault.agents>: map has no entry for key "agents"`

**Comment by 6l20** [comment]
That issue has not been reproduced
